export const BASE_PRODUCTS = [
  // ==========================================
  // 1. VIDEOJUEGOS FÍSICOS (VIDEO_GAME)
  // ==========================================
  {
    id: "prod-vg-pragmata",
    sku: "VG-PRAGMATA-PS5",
    name: "Pragmata [Juego PS5]",
    description: "Esta fusión de hackeo y disparos da como resultado una jugabilidad inmersiva, trepidante y estratégica, donde cada decisión influye en el resultado de la batalla.\n\nExplorar mediante habilidades especiales: El trabajo en equipo es importante tanto para el momento de explorar la estación de investigación lunar como de luchar.\n\nEn la estación lunar, usa los propulsores del traje de Hugh para moverte rápidamente por las instalaciones, mientras Diana hackea sus sistemas de seguridad, desbloquea puertas y despeja el camino para avanzar.\n\nMantente alerta en todo momento, porque aunque pueda parecer que las instalaciones están inquietantemente desiertas, siempre hay bots enemigos sin vida acechando en silencio.",
    type: "VIDEO_GAME" as const,
    price: 59900,
    originalPrice: 69900,
    costPrice: 42000,
    stockAvailable: 28,
    stockReserved: 0,
    isPreOrder: false,
    ageRating: "14+ 14 AÑOS O MÁS",
    genres: ["Acción", "Aventuras", "Ciencia Ficción"],
    trailerUrl: "https://www.youtube.com/watch?v=xoxCHe80A-w",
    imageUrl: "https://images.unsplash.com/photo-1542751371-adc38448a05e?w=800&auto=format&fit=crop&q=80",
    images: [
      "https://images.unsplash.com/photo-1542751371-adc38448a05e?w=800&auto=format&fit=crop&q=80",
    ],
    contentGallery: [
      "https://images.unsplash.com/photo-1511512578047-dfb367046420?w=1200&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=1200&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1563089145-599997674d42?w=1200&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=1200&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1538481199705-c710c4e965fc?w=1200&auto=format&fit=crop&q=80",
    ],
    gameMetadata: {
      id: "meta-vg-pragmata",
      productId: "prod-vg-pragmata",
      platform: "PS5" as const,
      edition: "STANDARD" as const,
      isDigital: false,
      publisher: "Capcom",
      audioLanguages: "Español - Inglés",
      subtitleLanguages: "Español - Inglés",
      players: "1 Jugador",
      fileSize: "55 GB",
      resolution: "4K 60fps / Ray Tracing / HDR",
    },
  },
  {
    id: "prod-vg-01",
    sku: "VG-ELDEN-PS5",
    name: "Elden Ring: Shadow of the Erdtree Edition (PS5)",
    description: "Edición física oficial sellada de fábrica con voucher de expansión Shadow of the Erdtree y despacho prioritario a todo Chile.",
    type: "VIDEO_GAME" as const,
    price: 79990,
    originalPrice: 89990,
    costPrice: 69990,
    stockAvailable: 25,
    stockReserved: 0,
    isPreOrder: false,
    ageRating: "18+ ADULTOS",
    genres: ["Acción", "RPG", "Mundo Abierto"],
    trailerUrl: "https://www.youtube.com/watch?v=AKXiKBnzpBQ",
    imageUrl: "https://images.unsplash.com/photo-1542751371-adc38448a05e?w=800&auto=format&fit=crop&q=80",
    images: [
      "https://images.unsplash.com/photo-1542751371-adc38448a05e?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=800&auto=format&fit=crop&q=80"
    ],
    contentGallery: [
      "https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=1200&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1511512578047-dfb367046420?w=1200&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1563089145-599997674d42?w=1200&auto=format&fit=crop&q=80",
    ],
    gameMetadata: {
      id: "meta-vg-01",
      productId: "prod-vg-01",
      platform: "PS5" as const,
      edition: "STANDARD" as const,
      isDigital: false,
      publisher: "Bandai Namco Entertainment",
      audioLanguages: "Inglés - Japonés",
      subtitleLanguages: "Español - Inglés",
      players: "1 Jugador (1 - 4 Online)",
      fileSize: "60 GB",
      resolution: "4K 60fps",
    },
  },
  {
    id: "prod-vg-02",
    sku: "VG-ZELDA-TOTK",
    name: "The Legend of Zelda: Tears of the Kingdom (Nintendo Switch)",
    description: "Edición física oficial en cartucho sellado de Nintendo. Aventura épica en el reino de Hyrule y los cielos con soporte de guardado en la nube.",
    type: "VIDEO_GAME" as const,
    price: 59990,
    costPrice: 46000,
    stockAvailable: 35,
    stockReserved: 0,
    isPreOrder: false,
    imageUrl: "https://images.unsplash.com/photo-1563089145-599997674d42?w=800&auto=format&fit=crop&q=80",
    images: [
      "https://images.unsplash.com/photo-1563089145-599997674d42?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=800&auto=format&fit=crop&q=80"
    ],
    gameMetadata: {
      id: "meta-vg-02",
      productId: "prod-vg-02",
      platform: "NINTENDO_SWITCH" as const,
      edition: "STANDARD" as const,
      isDigital: false,
      publisher: "Nintendo",
    },
  },
  {
    id: "prod-vg-03",
    sku: "VG-FF7-REBIRTH",
    name: "Final Fantasy VII Rebirth Deluxe Edition (PS5)",
    description: "Edición Deluxe en estuche Steelbook exclusivo con mini-artbook oficial, disco con banda sonora seleccionada y empaque holográfico.",
    type: "VIDEO_GAME" as const,
    price: 89990,
    costPrice: 72000,
    stockAvailable: 20,
    stockReserved: 0,
    isPreOrder: false,
    imageUrl: "https://images.unsplash.com/photo-1579373903781-fd5c0c30c4cd?w=800&auto=format&fit=crop&q=80",
    images: [
      "https://images.unsplash.com/photo-1579373903781-fd5c0c30c4cd?w=800&auto=format&fit=crop&q=80"
    ],
    gameMetadata: {
      id: "meta-vg-03",
      productId: "prod-vg-03",
      platform: "PS5" as const,
      edition: "DELUXE" as const,
      isDigital: false,
      publisher: "Square Enix",
    },
  },
  {
    id: "prod-vg-04",
    sku: "VG-METROID-PRIME",
    name: "Metroid Prime Remastered (Nintendo Switch)",
    description: "Remasterización en alta definición para Nintendo Switch del legendario FPS de exploración en primera persona con Samus Aran.",
    type: "VIDEO_GAME" as const,
    price: 44990,
    costPrice: 32000,
    stockAvailable: 28,
    stockReserved: 0,
    isPreOrder: false,
    imageUrl: "https://images.unsplash.com/photo-1612287233207-68b2f90a50e5?w=800&auto=format&fit=crop&q=80",
    images: [
      "https://images.unsplash.com/photo-1612287233207-68b2f90a50e5?w=800&auto=format&fit=crop&q=80"
    ],
    gameMetadata: {
      id: "meta-vg-04",
      productId: "prod-vg-04",
      platform: "NINTENDO_SWITCH" as const,
      edition: "STANDARD" as const,
      isDigital: false,
      publisher: "Nintendo",
    },
  },
  {
    id: "prod-vg-05",
    sku: "VG-SILENT-HILL-2",
    name: "Silent Hill 2 Remake Day One Edition (PS5)",
    description: "Regreso del clásico de terror psicológico desarrollado en Unreal Engine 5 por Bloober Team y Konami. Incluye máscara de Robbie the Rabbit.",
    type: "VIDEO_GAME" as const,
    price: 69990,
    costPrice: 54000,
    stockAvailable: 18,
    stockReserved: 0,
    isPreOrder: false,
    imageUrl: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=800&auto=format&fit=crop&q=80",
    images: [
      "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=800&auto=format&fit=crop&q=80"
    ],
    gameMetadata: {
      id: "meta-vg-05",
      productId: "prod-vg-05",
      platform: "PS5" as const,
      edition: "STANDARD" as const,
      isDigital: false,
      publisher: "Konami",
    },
  },
  {
    id: "prod-vg-06",
    sku: "VG-PERSONA3-RELOAD",
    name: "Persona 3 Reload Collector's Aigis Edition (PS5)",
    description: "Caja de colección monumental con figura oficial de Aigis, artbook con comentarios de Atlus, banda sonora en doble CD y paquete de trajes DLC.",
    type: "VIDEO_GAME" as const,
    price: 169990,
    costPrice: 125000,
    stockAvailable: 12,
    stockReserved: 0,
    isPreOrder: false,
    imageUrl: "https://images.unsplash.com/photo-1538481199705-c710c4e965fc?w=800&auto=format&fit=crop&q=80",
    images: [
      "https://images.unsplash.com/photo-1538481199705-c710c4e965fc?w=800&auto=format&fit=crop&q=80"
    ],
    gameMetadata: {
      id: "meta-vg-06",
      productId: "prod-vg-06",
      platform: "PS5" as const,
      edition: "COLLECTORS" as const,
      isDigital: false,
      publisher: "Atlus / SEGA",
    },
  },

  // ==========================================
  // 2. FIGURAS A ESCALA & NENDOROID (FIGURE)
  // ==========================================
  {
    id: "prod-fig-01",
    sku: "FIG-MAKIMA-17",
    name: "Makima 1/7 Scale PVC Figure (Chainsaw Man)",
    description: "Escala 1/7 licenciada de alta fidelidad, pintada a mano con base de diorama exclusiva.",
    type: "FIGURE" as const,
    price: 249990,
    costPrice: 160000,
    stockAvailable: 15,
    stockReserved: 0,
    isPreOrder: true,
    preOrderState: "PREORDER_OPEN" as const,
    imageUrl: "https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=800&auto=format&fit=crop&q=80",
    images: ["https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=800&auto=format&fit=crop&q=80"],
    figureMetadata: {
      id: "meta-fig-01",
      productId: "prod-fig-01",
      scale: "SCALE_1_7" as const,
      manufacturer: "GOOD_SMILE_COMPANY" as const,
      estimatedArrivalDate: "Noviembre 2026",
      allowsPartialDeposit: true,
      minimumDepositPercent: 0.2, // 20%
    },
  },
  {
    id: "prod-fig-02",
    sku: "FIG-LINK-NENDO",
    name: "Nendoroid Link: Tears of the Kingdom Ver.",
    description: "Figura articulada no a escala con partes intercambiables, espada maestra y base de display.",
    type: "FIGURE" as const,
    price: 64990,
    costPrice: 42000,
    stockAvailable: 40,
    stockReserved: 0,
    isPreOrder: true,
    preOrderState: "MANUFACTURING" as const,
    imageUrl: "https://images.unsplash.com/photo-1563089145-599997674d42?w=800&auto=format&fit=crop&q=80",
    images: ["https://images.unsplash.com/photo-1563089145-599997674d42?w=800&auto=format&fit=crop&q=80"],
    figureMetadata: {
      id: "meta-fig-02",
      productId: "prod-fig-02",
      scale: "NENDOROID" as const,
      manufacturer: "GOOD_SMILE_COMPANY" as const,
      estimatedArrivalDate: "Diciembre 2026",
      allowsPartialDeposit: true,
      minimumDepositPercent: 0.3, // 30%
    },
  },
  {
    id: "prod-fig-03",
    sku: "FIG-EVA01-METAL",
    name: "Evangelion Test Type-01 Metal Build (Bandai Spirits)",
    description: "Pieza maestra de aleación fundida y plásticos técnicos. Articulación múltiple de alta resistencia con rifle de positrones y cuchillo progresivo.",
    type: "FIGURE" as const,
    price: 299990,
    costPrice: 210000,
    stockAvailable: 8,
    stockReserved: 0,
    isPreOrder: false,
    imageUrl: "https://images.unsplash.com/photo-1560972550-aba3456b5564?w=800&auto=format&fit=crop&q=80",
    images: [
      "https://images.unsplash.com/photo-1560972550-aba3456b5564?w=800&auto=format&fit=crop&q=80"
    ],
    figureMetadata: {
      id: "meta-fig-03",
      productId: "prod-fig-03",
      scale: "ACTION_FIGURE" as const,
      manufacturer: "BANDAI_SPIRITS" as const,
      estimatedArrivalDate: "Disponible Inmediato",
      allowsPartialDeposit: false,
      minimumDepositPercent: 1.0,
    },
  },
  {
    id: "prod-fig-04",
    sku: "FIG-GOJO-17",
    name: "Satoru Gojo: Murasaki Hollow 1/7 Scale (Jujutsu Kaisen)",
    description: "Escultura prémium de Satoru Gojo liberando el Púrpura Hueco en el incidente de Shibuya. Base diorama con efectos translúcidos UV.",
    type: "FIGURE" as const,
    price: 269990,
    costPrice: 175000,
    stockAvailable: 14,
    stockReserved: 0,
    isPreOrder: true,
    preOrderState: "PREORDER_OPEN" as const,
    imageUrl: "https://images.unsplash.com/photo-1618336753974-aae8e04506aa?w=800&auto=format&fit=crop&q=80",
    images: [
      "https://images.unsplash.com/photo-1618336753974-aae8e04506aa?w=800&auto=format&fit=crop&q=80"
    ],
    figureMetadata: {
      id: "meta-fig-04",
      productId: "prod-fig-04",
      scale: "SCALE_1_7" as const,
      manufacturer: "KOTOBUKIYA" as const,
      estimatedArrivalDate: "Enero 2027",
      allowsPartialDeposit: true,
      minimumDepositPercent: 0.2, // 20%
    },
  },
  {
    id: "prod-fig-05",
    sku: "FIG-2B-FLARE",
    name: "2B (YoRHa No.2 Type B) DX Ver. 1/8 Scale (NieR:Automata)",
    description: "Escultura oficial fabricada por Flare con supervisión directa de Yoko Taro. Incluye Pod 042, cabeza sin visor y espada Virtuous Treaty.",
    type: "FIGURE" as const,
    price: 289990,
    costPrice: 195000,
    stockAvailable: 6,
    stockReserved: 0,
    isPreOrder: false,
    imageUrl: "https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=800&auto=format&fit=crop&q=80",
    images: [
      "https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=800&auto=format&fit=crop&q=80"
    ],
    figureMetadata: {
      id: "meta-fig-05",
      productId: "prod-fig-05",
      scale: "SCALE_1_8" as const,
      manufacturer: "ALTER" as const,
      estimatedArrivalDate: "Disponible Inmediato",
      allowsPartialDeposit: false,
      minimumDepositPercent: 1.0,
    },
  },
  {
    id: "prod-fig-06",
    sku: "FIG-FRIEREN-NENDO",
    name: "Nendoroid Frieren: Beyond Journey's End (Good Smile Company)",
    description: "La hechicera elfa Frieren en formato Nendoroid con báculo mágico, taza de té, grimorio de hechizos y rostro con expresión serena y cómica.",
    type: "FIGURE" as const,
    price: 59990,
    costPrice: 38000,
    stockAvailable: 30,
    stockReserved: 0,
    isPreOrder: false,
    imageUrl: "https://images.unsplash.com/photo-1563089145-599997674d42?w=800&auto=format&fit=crop&q=80",
    images: [
      "https://images.unsplash.com/photo-1563089145-599997674d42?w=800&auto=format&fit=crop&q=80"
    ],
    figureMetadata: {
      id: "meta-fig-06",
      productId: "prod-fig-06",
      scale: "NENDOROID" as const,
      manufacturer: "GOOD_SMILE_COMPANY" as const,
      estimatedArrivalDate: "Disponible Inmediato",
      allowsPartialDeposit: false,
      minimumDepositPercent: 1.0,
    },
  },
  {
    id: "prod-fig-07",
    sku: "FIG-GUTS-BERSERK",
    name: "Pop Up Parade L: Guts Berserker Armor Ver. (Berserk)",
    description: "Impresionante figura de 28 cm de alto con la armadura Berserker en pose de batalla. Ojos con efecto luminoso y pintura multicapa a mano.",
    type: "FIGURE" as const,
    price: 84990,
    costPrice: 58000,
    stockAvailable: 22,
    stockReserved: 0,
    isPreOrder: false,
    imageUrl: "https://images.unsplash.com/photo-1560972550-aba3456b5564?w=800&auto=format&fit=crop&q=80",
    images: [
      "https://images.unsplash.com/photo-1560972550-aba3456b5564?w=800&auto=format&fit=crop&q=80"
    ],
    figureMetadata: {
      id: "meta-fig-07",
      productId: "prod-fig-07",
      scale: "POP_UP_PARADE" as const,
      manufacturer: "MAX_FACTORY" as const,
      estimatedArrivalDate: "Disponible Inmediato",
      allowsPartialDeposit: false,
      minimumDepositPercent: 1.0,
    },
  },

  // ==========================================
  // 3. COLECCIONABLES TCG & MEMORABILIA (COLLECTIBLE)
  // ==========================================
  {
    id: "prod-col-01",
    sku: "TCG-CHARIZARD-PSA9",
    name: "Charizard 1st Edition Shadowless Base Set 4/102 (PSA 9 Mint)",
    description: "Carta coleccionable certificada con cápsula hermética UV y código QR de autenticación.",
    type: "COLLECTIBLE" as const,
    price: 4890000,
    costPrice: 4100000,
    stockAvailable: 1,
    stockReserved: 0,
    isPreOrder: false,
    imageUrl: "https://images.unsplash.com/photo-1613771404784-3a5686aa2be3?w=800&auto=format&fit=crop&q=80",
    images: ["https://images.unsplash.com/photo-1613771404784-3a5686aa2be3?w=800&auto=format&fit=crop&q=80"],
    collectibleMetadata: {
      id: "meta-col-01",
      productId: "prod-col-01",
      category: "TCG" as const,
      condition: "MINT_9" as const,
      cardLanguage: "English",
      authenticationBody: "PSA" as const,
      serialNumber: "PSA-88492019",
    },
  },
  {
    id: "prod-col-02",
    sku: "TCG-PIKACHU-CGC",
    name: "Pikachu Illustrator Promo Foil (CGC 8.5 NM/Mint+)",
    description: "Edición conmemorativa certificada por CGC en cápsula inviolable. Holograma original sin rayaduras y centrado casi perfecto.",
    type: "COLLECTIBLE" as const,
    price: 1290000,
    costPrice: 980000,
    stockAvailable: 2,
    stockReserved: 0,
    isPreOrder: false,
    imageUrl: "https://images.unsplash.com/photo-1613771404784-3a5686aa2be3?w=800&auto=format&fit=crop&q=80",
    images: ["https://images.unsplash.com/photo-1613771404784-3a5686aa2be3?w=800&auto=format&fit=crop&q=80"],
    collectibleMetadata: {
      id: "meta-col-02b",
      productId: "prod-col-02",
      category: "TCG" as const,
      condition: "NEAR_MINT_8" as const,
      cardLanguage: "Japanese",
      authenticationBody: "CGC" as const,
      serialNumber: "CGC-71829402",
    },
  },
  {
    id: "prod-col-03",
    sku: "TCG-BEWD-SDK001",
    name: "Blue-Eyes White Dragon 1st Edition SDK-001 (PSA 9 Mint)",
    description: "El mítico Dragón Blanco de Ojos Azules del muelle de Kaiba en su primera edición en inglés de 2002. Calificación 9 Mint de PSA.",
    type: "COLLECTIBLE" as const,
    price: 850000,
    costPrice: 620000,
    stockAvailable: 3,
    stockReserved: 0,
    isPreOrder: false,
    imageUrl: "https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=800&auto=format&fit=crop&q=80",
    images: ["https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=800&auto=format&fit=crop&q=80"],
    collectibleMetadata: {
      id: "meta-col-03b",
      productId: "prod-col-03",
      category: "TCG" as const,
      condition: "MINT_9" as const,
      cardLanguage: "English",
      authenticationBody: "PSA" as const,
      serialNumber: "PSA-99014238",
    },
  },
  {
    id: "prod-col-04",
    sku: "TCG-LUFFY-GEAR5",
    name: "Monkey D. Luffy Gear 5 Manga Foil (BGS 9.5 Gem Mint)",
    description: "Carta de líder exclusiva de One Piece Card Game (Japón) con arte original de Eiichiro Oda y gradación Gem Mint 9.5 por Beckett (BGS).",
    type: "COLLECTIBLE" as const,
    price: 420000,
    costPrice: 290000,
    stockAvailable: 5,
    stockReserved: 0,
    isPreOrder: false,
    imageUrl: "https://images.unsplash.com/photo-1618336753974-aae8e04506aa?w=800&auto=format&fit=crop&q=80",
    images: ["https://images.unsplash.com/photo-1618336753974-aae8e04506aa?w=800&auto=format&fit=crop&q=80"],
    collectibleMetadata: {
      id: "meta-col-04b",
      productId: "prod-col-04",
      category: "TCG" as const,
      condition: "GEM_MINT_10" as const,
      cardLanguage: "Japanese",
      authenticationBody: "BGS" as const,
      serialNumber: "BGS-8491023",
    },
  },
  {
    id: "prod-acc-01",
    sku: "ACC-PIN-SET",
    name: "Elden Enamel Pin Collector's Set",
    description: "Juego de 3 pines esmaltados metálicos con acabado en oro antiguo.",
    type: "COLLECTIBLE" as const,
    price: 24990,
    costPrice: 8000,
    stockAvailable: 50,
    stockReserved: 0,
    isPreOrder: false,
    imageUrl: "https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=800&auto=format&fit=crop&q=80",
    images: ["https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=800&auto=format&fit=crop&q=80"],
    collectibleMetadata: {
      id: "meta-col-02",
      productId: "prod-acc-01",
      category: "MEMORABILIA" as const,
      condition: "GEM_MINT_10" as const,
      authenticationBody: "NONE" as const,
    },
  },
  {
    id: "prod-acc-02",
    sku: "ACC-ARTBOOK",
    name: "Lands Between Deluxe Artbook (Hardcover)",
    description: "Libro de arte oficial de tapa dura con 250 páginas a todo color.",
    type: "COLLECTIBLE" as const,
    price: 44990,
    costPrice: 20000,
    stockAvailable: 30,
    stockReserved: 0,
    isPreOrder: false,
    imageUrl: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=800&auto=format&fit=crop&q=80",
    images: ["https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=800&auto=format&fit=crop&q=80"],
    collectibleMetadata: {
      id: "meta-col-03",
      productId: "prod-acc-02",
      category: "MEMORABILIA" as const,
      condition: "GEM_MINT_10" as const,
      authenticationBody: "NONE" as const,
    },
  },
  {
    id: "prod-acc-03",
    sku: "ACC-SWORD-MASTER",
    name: "Réplica Espada Maestra Zelda (Acero Templado 1:1)",
    description: "Réplica de exhibición a escala real con hoja de acero inoxidable, empuñadura forrada en cuero azul y peana de exposición para muro.",
    type: "COLLECTIBLE" as const,
    price: 139990,
    costPrice: 85000,
    stockAvailable: 10,
    stockReserved: 0,
    isPreOrder: false,
    imageUrl: "https://images.unsplash.com/photo-1563089145-599997674d42?w=800&auto=format&fit=crop&q=80",
    images: ["https://images.unsplash.com/photo-1563089145-599997674d42?w=800&auto=format&fit=crop&q=80"],
    collectibleMetadata: {
      id: "meta-col-05b",
      productId: "prod-acc-03",
      category: "MEMORABILIA" as const,
      condition: "GEM_MINT_10" as const,
      authenticationBody: "NONE" as const,
    },
  },

  // ==========================================
  // 4. BUNDLES COMPUESTOS EXCLUSIVOS (BUNDLE)
  // ==========================================
  {
    id: "prod-bun-01",
    sku: "BUN-ELDEN-MASTER",
    name: "Elden Lord Ultimate Collector Bundle (Game + Pins + Artbook)",
    description: "Bundle exclusivo: Videojuego PS5 + Set de Pines Esmaltados + Hardcover Artbook. Inventario atómico sincronizado.",
    type: "BUNDLE" as const,
    price: 124990,
    costPrice: 97990,
    stockAvailable: 0,
    stockReserved: 0,
    isPreOrder: false,
    imageUrl: "https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=800&auto=format&fit=crop&q=80",
    images: ["https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=800&auto=format&fit=crop&q=80"],
    calculatedAvailableStock: 25,
    aggregateMarginPercent: 21.6,
    nominalSumOfItems: 149970,
  },
  {
    id: "prod-bun-02",
    sku: "BUN-ZELDA-HERO",
    name: "Hyrule Hero Master Pack (Zelda TotK + Nendoroid Link + Espada)",
    description: "El paquete supremo para fanáticos de The Legend of Zelda: Juego físico Switch + Figura Nendoroid oficial + Réplica 1:1 de la Espada Maestra.",
    type: "BUNDLE" as const,
    price: 229990,
    costPrice: 173000,
    stockAvailable: 0,
    stockReserved: 0,
    isPreOrder: false,
    imageUrl: "https://images.unsplash.com/photo-1563089145-599997674d42?w=800&auto=format&fit=crop&q=80",
    images: ["https://images.unsplash.com/photo-1563089145-599997674d42?w=800&auto=format&fit=crop&q=80"],
    calculatedAvailableStock: 10,
    aggregateMarginPercent: 24.8,
    nominalSumOfItems: 264970,
  },

  // ==========================================
  // 5. CONSOLAS DE VIDEOJUEGOS (CONSOLE)
  // ==========================================
  {
    id: "prod-con-01",
    sku: "CON-PS5-SLIM-DIG",
    name: "PlayStation 5 Slim Digital Edition 1TB SSD",
    description: "Consola oficial PlayStation 5 modelo Slim de 1TB de almacenamiento ultra rápido, diseño compacto y control inalámbrico DualSense con respuesta háptica.",
    type: "CONSOLE" as const,
    customCategoryLabel: "Consolas",
    price: 469990,
    originalPrice: 499990,
    costPrice: 380000,
    stockAvailable: 6,
    stockReserved: 0,
    isPreOrder: false,
    imageUrl: "https://images.unsplash.com/photo-1606813907291-d86efa9b94db?w=800&auto=format&fit=crop&q=80",
    images: ["https://images.unsplash.com/photo-1606813907291-d86efa9b94db?w=800&auto=format&fit=crop&q=80"],
    customSpecifications: {
      categoryType: "CONSOLE",
      console: {
        baseModel: "PlayStation 5 Slim Digital Edition",
        capacity: "1 TB SSD NVMe Ultrarrápido",
        format: "Digital Edition (Sin lector óptico)",
        controllersIncluded: "1x Control Inalámbrico DualSense Blanco",
        bundleIncluded: "Consola, Mando DualSense, Cable HDMI 2.1, Cable USB-C, Cable de poder, ASTRO's PLAYROOM preinstalado",
        ports: "1x HDMI 2.1, 2x USB-C frontales, 2x USB-A 3.2 traseros, Gigabit LAN, Wi-Fi 6",
        gameCompatibility: "Compatible con catálogo digital completo de PS5 y más de 4.000 títulos de PS4",
        featuredHighlights: "Audio Tempest 3D, Ray Tracing por hardware, salida 4K a 120 fps y tiempos de carga instantáneos",
      },
    },
  },

  // ==========================================
  // 6. HARDWARE & COMPONENTES (HARDWARE)
  // ==========================================
  {
    id: "prod-hw-01",
    sku: "HW-SSD-SAMS-990PRO-2TB",
    name: "SSD Samsung 990 PRO 2TB NVMe M.2 con Disipador Heatsink (PCIe 4.0)",
    description: "Unidad de almacenamiento de estado sólido de alto rendimiento Samsung 990 PRO 2TB con disipador térmico incorporado, velocidad de lectura de 7.450 MB/s, 100% compatible con expansión de almacenamiento interno de PlayStation 5 y PC Gaming de gama alta.",
    type: "HARDWARE" as const,
    customCategoryLabel: "Hardware & Componentes",
    price: 189990,
    originalPrice: 219990,
    costPrice: 135000,
    stockAvailable: 12,
    stockReserved: 0,
    isPreOrder: false,
    imageUrl: "https://images.unsplash.com/photo-1587202372775-e229f172b9d7?w=800&auto=format&fit=crop&q=80",
    images: ["https://images.unsplash.com/photo-1587202372775-e229f172b9d7?w=800&auto=format&fit=crop&q=80"],
    customSpecifications: {
      categoryType: "HARDWARE",
      hardware: {
        componentType: "Almacenamiento SSD NVMe M.2",
        brand: "Samsung",
        model: "990 PRO con Heatsink",
        interfaceOrSocket: "PCIe 4.0 x4, NVMe 2.0 (M.2 2280)",
        capacityOrSpeed: "2 TB (Lectura: 7.450 MB/s, Escritura: 6.900 MB/s)",
        formFactor: "M.2 2280 con disipador térmico (80 x 24.3 x 8.2 mm)",
        powerConsumptionTdp: "8.5W máx / Certificado para PS5 y PC",
        warrantyYears: "5 años de garantía limitada oficial o 1.200 TBW",
        featuredHighlights: "Control térmico inteligente de níquel, tecnología V-NAND TLC, optimizado para cargas pesadas de renderizado y tiempos de carga instantáneos en juegos AAA",
      },
    },
  },
];

export const PRICE_PRESETS = [
  { label: "< $50.000", min: "", max: "50000" },
  { label: "$50k - $150k", min: "50000", max: "150000" },
  { label: "$150k - $500k", min: "150000", max: "500000" },
  { label: "> $500.000", min: "500000", max: "" },
];
