import type { ProductDomainEntity } from "../types/domain";

/**
 * Isolated test catalog used strictly in Vitest/Jest test suites
 * to test transactional domain logic (preorders, concurrency, bundles).
 * In production and development, this is never loaded.
 */
export const TEST_MOCK_PRODUCTS: ProductDomainEntity[] = [
  {
    id: "prod-vg-01",
    sku: "VG-ELDEN-PS5",
    name: "Elden Ring: Shadow of the Erdtree Edition (PS5)",
    description: "Edición física oficial sellada de fábrica con voucher de expansión.",
    type: "VIDEO_GAME",
    price: 79990,
    originalPrice: 89990,
    costPrice: 69990,
    stockAvailable: 25,
    stockReserved: 0,
    isPreOrder: false,
    createdAt: "2026-08-01T00:00:00.000Z",
    gameMetadata: {
      id: "meta-vg-01",
      productId: "prod-vg-01",
      platform: "PS5",
      edition: "STANDARD",
      isDigital: false,
      publisher: "Bandai Namco Entertainment",
    },
  },
  {
    id: "prod-vg-02",
    sku: "VG-ZELDA-TOTK",
    name: "The Legend of Zelda: Tears of the Kingdom (Nintendo Switch)",
    description: "Edición física oficial en cartucho sellado de Nintendo.",
    type: "VIDEO_GAME",
    price: 59990,
    costPrice: 46000,
    stockAvailable: 35,
    stockReserved: 0,
    isPreOrder: false,
    createdAt: "2026-08-01T00:00:00.000Z",
    gameMetadata: {
      id: "meta-vg-02",
      productId: "prod-vg-02",
      platform: "NINTENDO_SWITCH",
      edition: "STANDARD",
      isDigital: false,
      publisher: "Nintendo",
    },
  },
  {
    id: "prod-fig-01",
    sku: "FIG-MAKIMA-1-7",
    name: "Makima 1/7 Scale PVC Figure (Good Smile Company)",
    description: "Figura oficial japonesa a escala 1/7 de Makima (Chainsaw Man).",
    type: "FIGURE",
    price: 249990,
    originalPrice: 279990,
    costPrice: 180000,
    stockAvailable: 15,
    stockReserved: 0,
    isPreOrder: true,
    preOrderState: "PREORDER_OPEN",
    createdAt: "2026-08-01T00:00:00.000Z",
    figureMetadata: {
      id: "meta-fig-01",
      productId: "prod-fig-01",
      scale: "SCALE_1_7",
      manufacturer: "GOOD_SMILE_COMPANY",
      estimatedArrivalDate: "Q4 2026",
      allowsPartialDeposit: true,
      minimumDepositPercent: 0.2,
      material: "PVC / ABS",
      dimensions: "28 cm con peana",
    },
  },
  {
    id: "prod-fig-02",
    sku: "FIG-LINK-NENDO",
    name: "Nendoroid Link: Tears of the Kingdom Ver.",
    description: "Figura Nendoroid articulada oficial con múltiples accesorios intercambiables.",
    type: "FIGURE",
    price: 64990,
    costPrice: 42000,
    stockAvailable: 40,
    stockReserved: 0,
    isPreOrder: true,
    preOrderState: "MANUFACTURING",
    createdAt: "2026-08-01T00:00:00.000Z",
    figureMetadata: {
      id: "meta-fig-02",
      productId: "prod-fig-02",
      scale: "NON_SCALE",
      manufacturer: "GOOD_SMILE_COMPANY",
      estimatedArrivalDate: "Q3 2026",
      allowsPartialDeposit: true,
      minimumDepositPercent: 0.3,
      material: "PVC",
    },
  },
  {
    id: "prod-col-01",
    sku: "TCG-CHARIZARD-BASE-PSA9",
    name: "Charizard Base Set 1st Edition Shadowless (PSA 9 Mint)",
    description: "Pieza histórica certificada por PSA con grado 9 Mint.",
    type: "COLLECTIBLE",
    price: 3499990,
    costPrice: 2800000,
    stockAvailable: 1,
    stockReserved: 0,
    isPreOrder: false,
    createdAt: "2026-08-01T00:00:00.000Z",
    collectibleMetadata: {
      id: "meta-col-01",
      productId: "prod-col-01",
      category: "TCG",
      condition: "MINT_9",
      cardLanguage: "English",
      authenticationBody: "PSA",
      serialNumber: "PSA-64829104",
      gradeScore: "9",
    },
  },
  {
    id: "prod-acc-01",
    sku: "ACC-PIN-SET",
    name: "Elden Enamel Pin Collector's Set",
    description: "Juego de 3 pines esmaltados metálicos con acabado en oro antiguo.",
    type: "COLLECTIBLE",
    price: 24990,
    costPrice: 8000,
    stockAvailable: 50,
    stockReserved: 0,
    isPreOrder: false,
    createdAt: "2026-08-01T00:00:00.000Z",
  },
  {
    id: "prod-acc-02",
    sku: "ACC-ARTBOOK",
    name: "Lands Between Deluxe Artbook (Hardcover)",
    description: "Libro de arte oficial de tapa dura con 250 páginas a todo color.",
    type: "COLLECTIBLE",
    price: 44990,
    costPrice: 20000,
    stockAvailable: 30,
    stockReserved: 0,
    isPreOrder: false,
    createdAt: "2026-08-01T00:00:00.000Z",
  },
  {
    id: "prod-acc-03",
    sku: "ACC-SWORD-MASTER",
    name: "Réplica Espada Maestra Zelda (Acero Templado 1:1)",
    description: "Réplica de exhibición a escala real.",
    type: "COLLECTIBLE",
    price: 139990,
    costPrice: 85000,
    stockAvailable: 10,
    stockReserved: 0,
    isPreOrder: false,
    createdAt: "2026-08-01T00:00:00.000Z",
  },
  {
    id: "prod-bun-01",
    sku: "BUN-ELDEN-MASTER",
    name: "Elden Lord Ultimate Collector Bundle (Game + Pins + Artbook)",
    description: "Bundle exclusivo: Videojuego PS5 + Set de Pines + Hardcover Artbook.",
    type: "BUNDLE",
    price: 124990,
    costPrice: 97990,
    stockAvailable: 0,
    stockReserved: 0,
    isPreOrder: false,
    calculatedAvailableStock: 25,
    aggregateMarginPercent: 21.6,
    nominalSumOfItems: 149970,
    createdAt: "2026-08-01T00:00:00.000Z",
    bundleComponents: [
      {
        componentProductId: "prod-vg-01",
        sku: "VG-ELDEN-PS5",
        name: "Elden Ring PS5",
        quantity: 1,
        unitPrice: 79990,
        unitCost: 69990,
        availableStock: 25,
      },
      {
        componentProductId: "prod-acc-01",
        sku: "ACC-PIN-SET",
        name: "Elden Enamel Pin Set",
        quantity: 1,
        unitPrice: 24990,
        unitCost: 8000,
        availableStock: 50,
      },
      {
        componentProductId: "prod-acc-02",
        sku: "ACC-ARTBOOK",
        name: "Lands Between Artbook",
        quantity: 1,
        unitPrice: 44990,
        unitCost: 20000,
        availableStock: 30,
      },
    ],
  },
  {
    id: "prod-bun-02",
    sku: "BUN-ZELDA-HERO",
    name: "Hyrule Hero Master Pack (Zelda TotK + Nendoroid Link + Espada)",
    description: "El paquete supremo para fanáticos de The Legend of Zelda.",
    type: "BUNDLE",
    price: 229990,
    costPrice: 173000,
    stockAvailable: 0,
    stockReserved: 0,
    isPreOrder: false,
    calculatedAvailableStock: 10,
    aggregateMarginPercent: 24.8,
    nominalSumOfItems: 264970,
    createdAt: "2026-08-01T00:00:00.000Z",
    bundleComponents: [
      {
        componentProductId: "prod-vg-02",
        sku: "VG-ZELDA-TOTK",
        name: "Zelda TotK Switch",
        quantity: 1,
        unitPrice: 59990,
        unitCost: 46000,
        availableStock: 35,
      },
      {
        componentProductId: "prod-fig-02",
        sku: "FIG-LINK-NENDO",
        name: "Nendoroid Link",
        quantity: 1,
        unitPrice: 64990,
        unitCost: 42000,
        availableStock: 40,
      },
      {
        componentProductId: "prod-acc-03",
        sku: "ACC-SWORD-MASTER",
        name: "Réplica Espada Maestra Zelda",
        quantity: 1,
        unitPrice: 139990,
        unitCost: 85000,
        availableStock: 10,
      },
    ],
  },
];
