"use client";
import React, { useState, useEffect, useRef } from "react";
import Link from "next/link";
import { ArrowRight, ArrowLeft, Terminal, ShieldCheck, Palette, Package, ArrowLeftRight, ScanLine, Check, Gamepad2, Sparkles } from "lucide-react";
import { Button } from "@/components/ui/button";
import { formatCLP } from "@/lib/utils/currency";
const stops = [
  { title: "Elige tu universo", subtitle: "Catálogo y comparación", icon: ArrowLeftRight },
  { title: "Una imagen, una pista", subtitle: "Identificación visual con IA", icon: ScanLine },
  { title: "Cada unidad cuenta", subtitle: "Inventario y preventas", icon: Package },
  { title: "Tu tienda, tu identidad", subtitle: "Personalización visual", icon: Palette },
  { title: "Cambios con memoria", subtitle: "Versiones y auditoría", icon: Terminal },
  { title: "Control detrás de escena", subtitle: "Seguridad y cuotas IA", icon: ShieldCheck },
];
const demoItems = [{ name: "Aventura espacial · Edición de colección", price: 54990, platform: "PS5", edition: "Coleccionista" }, { name: "Aventura espacial · Edición estándar", price: 39990, platform: "PS5", edition: "Estándar" }];
const trace = ["Imagen seleccionada por el visitante", "Modelo analiza la imagen en el servidor", "La respuesta se valida antes de usarla", "Se consultan productos del catálogo actual", "La consola muestra resultados y coincidencias"];
export default function PortfolioPage() {
  const [step, setStep] = useState(0); const [traceStep, setTraceStep] = useState(0);
  const [reserved, setReserved] = useState(false); const [accent, setAccent] = useState("#FF6B35");
  const [heading, setHeading] = useState("Tu próxima pieza."); const [saved, setSaved] = useState<string[]>(["Diseño original"]);
  const [compared, setCompared] = useState(false);
  const stageRef = useRef<HTMLElement>(null); const previousStep = useRef(step);
  useEffect(() => {
    if (previousStep.current === step) return;
    previousStep.current = step;
    stageRef.current?.scrollIntoView?.({ block: "start", behavior: window.matchMedia?.("(prefers-reduced-motion: reduce)").matches ? "auto" : "smooth" });
    stageRef.current?.focus({ preventScroll: true });
  }, [step]);
  const current = stops[step]; const Icon = current.icon;
  return <div className="mx-auto max-w-7xl px-4 sm:px-6 py-10 sm:py-16 space-y-10">
    <header className="grid lg:grid-cols-[1.3fr_1fr] gap-8 items-center"><div><span className="inline-flex gap-2 items-center rounded-full border bg-white px-3 py-2 text-xs font-semibold text-[#1F3A5F]"><Sparkles size={14} className="text-[#FF6B35]"/>Laboratorio de portafolio</span><h1 className="text-4xl sm:text-6xl font-semibold tracking-tight text-[#1F3A5F] leading-tight mt-5">Más que una vitrina.<br/><span className="text-[#FF6B35]">Explora cómo funciona.</span></h1><p className="text-slate-600 leading-relaxed mt-5 max-w-xl">Un recorrido interactivo por el catálogo, la IA, el inventario y el panel de OmniCollector.</p></div><aside className="rounded-3xl bg-[#1F3A5F] text-white p-7 space-y-3"><ShieldCheck className="text-emerald-300" size={30}/><h2 className="font-bold text-xl">Puedes experimentar aquí</h2><p className="text-sm text-slate-200 leading-relaxed">Estos ejemplos usan datos ficticios y estado local. No se conectan a pagos, no consultan modelos IA ni modifican la tienda o la base de datos. El panel administrativo real conserva su acceso protegido.</p><Link href="/catalog" className="inline-flex gap-2 items-center text-sm font-bold text-orange-200">Ver el catálogo real<ArrowRight size={16}/></Link></aside></header>
    <div className="grid lg:grid-cols-[270px_1fr] gap-6"><nav aria-label="Etapas del recorrido" className="grid sm:grid-cols-2 lg:grid-cols-1 gap-2 self-start">{stops.map((stop, index) => { const StopIcon = stop.icon; return <button key={stop.title} aria-current={index === step ? "step" : undefined} onClick={() => setStep(index)} className={"rounded-2xl border p-4 text-left flex gap-3 items-start " + (index === step ? "bg-[#1F3A5F] text-white border-[#1F3A5F]" : "bg-white text-[#1F3A5F] hover:border-[#FF6B35]")}><StopIcon className="shrink-0 mt-1" size={20}/><span><strong className="text-sm block">{index + 1}. {stop.title}</strong><span className="text-xs opacity-75 mt-1 block">{stop.subtitle}</span></span></button>; })}</nav>
    <section ref={stageRef} tabIndex={-1} aria-labelledby="portfolio-stage-heading" className="rounded-3xl border bg-white p-5 sm:p-8 min-w-0 scroll-mt-28 outline-none focus-visible:ring-2 focus-visible:ring-[#FF6B35]"><header className="flex gap-3 items-center text-[#1F3A5F] mb-7"><Icon className="text-[#FF6B35]" size={26}/><div><p className="text-xs text-slate-500">Ejemplo local · Paso {step + 1} de 6</p><h2 id="portfolio-stage-heading" className="text-2xl font-bold mt-1">{current.subtitle}</h2></div></header>
    {step === 0 && <div className="space-y-5"><p className="text-sm text-slate-600">El comparador real combina precio, disponibilidad y ficha técnica de hasta tres productos vigentes.</p><div className="grid sm:grid-cols-2 gap-4">{demoItems.map(item => <article key={item.name} className="rounded-2xl border bg-slate-50 p-5"><div className="h-28 bg-gradient-to-br from-[#DCE6F0] to-white rounded-xl mb-4 grid place-items-center"><Gamepad2 size={55} className="text-[#1F3A5F]"/></div><h3 className="font-bold text-[#1F3A5F]">{item.name}</h3><p className="text-[#FF6B35] font-bold mt-2">{formatCLP(item.price)}</p></article>)}</div><Button onClick={() => setCompared(!compared)}><ArrowLeftRight size={16}/>{compared ? "Ocultar comparación" : "Comparar estos ejemplos"}</Button>{compared && <div className="overflow-x-auto"><table className="w-full text-sm text-left"><caption className="sr-only">Comparación de productos ficticios</caption><thead><tr><th className="p-3">Ficha</th>{demoItems.map(item => <th key={item.name} className="p-3">{item.edition}</th>)}</tr></thead><tbody>{[["Precio", ...demoItems.map(item => formatCLP(item.price))], ["Plataforma", "PS5", "PS5"]].map(row => <tr key={row[0]} className="border-t">{row.map((value, i) => i === 0 ? <th className="p-3" key={i} scope="row">{value}</th> : <td className="p-3" key={i}>{value}</td>)}</tr>)}</tbody></table></div>}</div>}
    {step === 1 && <div className="space-y-5"><p className="text-sm text-slate-600">La función real muestra eventos del servidor. Este ejemplo explica esas etapas con controles manuales, sin ejecutar una consulta IA.</p><div className="rounded-2xl bg-[#061C25] border border-cyan-700 text-cyan-200 p-5 font-mono shadow-[0_0_30px_#22d3ee15]"><p className="text-xs text-fuchsia-300 border-b border-cyan-900 pb-3">OMNI VISION // SIMULACIÓN INTERACTIVA</p><ol className="space-y-4 my-5">{trace.map((line, index) => <li key={line} className={"flex items-center gap-3 text-xs sm:text-sm " + (index <= traceStep ? "text-cyan-200" : "text-slate-600")}><span>{index <= traceStep ? "[✓]" : "[ ]"}</span>{line}</li>)}</ol>{traceStep === trace.length - 1 && <p className="rounded-xl bg-cyan-950 p-3 text-sm">Ejemplo: videojuego para PS5 · Los resultados reales dependen del catálogo y del análisis de la imagen.</p>}</div><div className="flex gap-3"><Button disabled={traceStep === trace.length - 1} onClick={() => setTraceStep(value => value + 1)}>Ver siguiente etapa<ArrowRight size={16}/></Button><Button variant="outline" onClick={() => setTraceStep(0)}>Reiniciar</Button></div></div>}
    {step === 2 && <div className="space-y-5"><p className="text-sm text-slate-600">En la tienda, las reservas se coordinan en transacciones para proteger el inventario. Aquí puedes probar el cálculo de una preventa con depósito del 20%.</p><div className="grid sm:grid-cols-3 gap-3">{[["Unidades físicas", "2"], ["Reservadas", reserved ? "1" : "0"], ["Disponibles", reserved ? "1" : "2"]].map(([label, value]) => <div key={label} className="rounded-2xl bg-[#1F3A5F] text-white p-5"><p className="text-xs text-slate-300">{label}</p><strong className="text-4xl block mt-2">{value}</strong></div>)}</div><div className="rounded-2xl border p-5 text-sm space-y-2"><p>Precio del ejemplo: <strong>{formatCLP(59990)}</strong></p><p>Depósito: <strong>{formatCLP(Math.round(59990 * .2))}</strong></p><p>Saldo: <strong>{formatCLP(59990 - Math.round(59990 * .2))}</strong></p></div><Button onClick={() => setReserved(!reserved)}>{reserved ? "Liberar reserva del ejemplo" : "Simular una reserva"}</Button><p role="status" className="text-xs text-slate-500">{reserved ? "Una unidad reservada únicamente en esta demostración." : "Ninguna reserva activa en este ejemplo."}</p></div>}
    {step === 3 && <div className="space-y-5"><p className="text-sm text-slate-600">El editor real permite elegir textos y un producto vigente, con vista previa antes de guardar. Prueba una identidad alternativa aquí.</p><label className="grid gap-2 text-sm">Título del ejemplo<input value={heading} maxLength={70} onChange={event => setHeading(event.target.value)} className="border rounded-xl p-3"/></label><div className="flex gap-3" aria-label="Colores del ejemplo">{["#FF6B35", "#0891B2", "#7C3AED"].map(color => <button key={color} onClick={() => setAccent(color)} aria-label={"Elegir color " + color} aria-pressed={color === accent} style={{ background: color }} className="h-10 w-10 rounded-full grid place-items-center text-white">{color === accent && <Check size={18}/>}</button>)}</div><div className="rounded-3xl bg-[#F2F5F8] p-8 sm:p-12 space-y-5"><p className="text-xs uppercase tracking-widest text-slate-500">Vista previa local</p><h3 className="text-3xl sm:text-5xl font-bold break-words text-[#1F3A5F]">{heading || "Tu próxima pieza."}<br/><span style={{ color: accent }}>Tu próxima historia.</span></h3><span style={{ background: accent }} className="inline-block rounded-full px-5 py-3 text-sm text-white font-bold">Explorar mi universo</span></div></div>}
    {step === 4 && <div className="space-y-5"><p className="text-sm text-slate-600">Los cambios reales y su auditoría se guardan juntos. Las versiones visuales permiten nombrar campañas y recuperar diseños anteriores.</p><Button disabled={saved.length >= 5} onClick={() => setSaved(current => [...current, heading || "Diseño de ejemplo"])}><Palette size={16}/>Capturar título del ejemplo</Button><ol className="space-y-3">{saved.map((value, index) => <li key={index} className="rounded-2xl border p-4 flex justify-between gap-3 items-center"><div><strong className="text-[#1F3A5F]">{value}</strong><p className="text-xs text-slate-500 mt-1">Versión {index + 1} · Visitante de demostración · solo en esta página</p></div><Button variant="outline" onClick={() => { setHeading(value); setStep(3); }}>Ver diseño</Button></li>)}</ol><p className="text-xs text-slate-500">Estas versiones desaparecen al actualizar. El historial del panel real persiste en Firestore.</p></div>}
    {step === 5 && <div className="space-y-5"><p className="text-sm text-slate-600">La seguridad real se aplica en el servidor. La interfaz no decide quién puede administrar.</p>{[["Identidad verificada", "Las API privadas comprueban tokens Firebase y sesiones administrativas firmadas."], ["Base de datos protegida", "Las reglas preparadas reservan las escrituras a API del servidor y limitan las lecturas privadas al propietario."], ["IA con límites", "Cuotas diarias por cuenta/visitante y una reserva global evitan consultas ilimitadas."], ["App Check configurable", "Observación primero; exigencia de reCAPTCHA después de registrarlo y verificarlo."]].map(([title, text]) => <article key={title} className="flex gap-3 rounded-2xl border p-5"><ShieldCheck className="text-emerald-600 shrink-0" size={20}/><div><h3 className="font-bold text-[#1F3A5F]">{title}</h3><p className="text-sm text-slate-600 mt-1">{text}</p></div></article>)}<Link href="/catalog" className="inline-flex items-center gap-2 text-[#FF6B35] font-bold">Explorar la tienda<ArrowRight size={17}/></Link></div>}
    <footer className="flex items-center justify-between gap-3 mt-8 pt-5 border-t"><Button variant="outline" disabled={step === 0} onClick={() => setStep(step - 1)}><ArrowLeft size={16}/>Anterior</Button><span className="text-xs text-slate-500">{step + 1} / {stops.length}</span><Button disabled={step === stops.length - 1} onClick={() => setStep(step + 1)}>Siguiente<ArrowRight size={16}/></Button></footer>
    </section></div>
  </div>;
}
